REM   Script: Session 04
REM   FINAL1.

CREATE TABLE EMPLOYEE ( 
    EMPLOYEEID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    EMAIL_ID varchar (255), 
    PHONE_NUMBER int, 
    HIRING_DATE INT, 
    SALARY INT 
);

INSERT INTO EMPLOYEE VALUES(1,'AHAMED','SUHAIL','ahamedsuhail2412@GMAIL.COM',8220548132,09/08/2022,24000);

INSERT INTO EMPLOYEE VALUES(2,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(3,'AJMUL','KANI','ajmulgani4567@GMAIL.COM',8056570129,18/12/2019,40000);

INSERT INTO EMPLOYEE VALUES(4,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(5,'HARI','HARAN','hariharan4545@GMAIL.COM',8220564563,29/03/2020,30000);

INSERT INTO EMPLOYEE VALUES(6,'JANOFER','NISHA','janofernisha4321@GMAIL.COM',8220568473,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(7,'SATHIS','KUMAR','sathiskumar9045@GMAIL.COM',8220563784,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(8,'RANJITH','KUMAR','ranjithkumar5645@GMAIL.COM',8220567434,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(9,'BASITH','ALI','basithali8745@GMAIL.COM',8220561455,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(10,'TAMIL','SELVI','tamilselvi9845@GMAIL.COM',8220561352,29/09/2018,50000);

SELECT * FROM EMPLOYEE;

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int 
     
);

INSERT INTO DEPARTMENT VALUES(1,'AHAMED SUHAIL','3/79 RAMAZAN STREET ATHIYUTHU','RAMANATHAPURAM','INDIA',623513);

INSERT INTO DEPARTMENT VALUES(2,'SRI KARN','3/98 NEW STREET PANAIKULAM','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(3,'SATHIS KUMAR','4/55S EAST STREET CHITTORKOTTAI','RAMANATHAPURAM','INDIA',623534);

INSERT INTO DEPARTMENT VALUES(4,'JANOFER NISHA','4/R3 WEST STREET PUTHUVALASI','RAMANATHAPURAM','INDIA',623523);

INSERT INTO DEPARTMENT VALUES(5,'RANJITH KUMAR','33/R4 NORTH STREET THERBOKI','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(6,'HARI HARAN','4/4R SOUTH STREET KOVILKARAI','RAMANATHAPURAM','INDIA',623511);

INSERT INTO DEPARTMENT VALUES(7,'AJMUL KANI','3/33L RAMALAN STREET ALAGANKULAM','RAMANATHAPURAM','INDIA',623514);

INSERT INTO DEPARTMENT VALUES(8,'SINDHU SRI','3/34LD KOVIL STREET ATTANKARAI','RAMANATHAPURAM','INDIA',623515);

INSERT INTO DEPARTMENT VALUES(9,'TAMIL SELVI','324D/3W KAVAL STREET MANDAPAM','RAMANATHAPURAM','INDIA',623518);

INSERT INTO DEPARTMENT VALUES(10,'BASITH ALI','3/89L OLD STREET RAMALAN NAGAR','RAMANATHAPURAM','INDIA',623517);

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID=A1 WHERE CUSTOMER_ID=1;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=6;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=7;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=9;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=9;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=5;

SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.DEPARTMENT_ID,EMPLOYEE.DEPARTMENT_ID 
 FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMEN;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ELECT * FROM EMPLOYEE


SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE DROP COLUMN DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT DROP COLUMN DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='012' WHERE CUSTOMER_ID=9;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='015' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='005' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='025' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='06' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='009' WHERE CUSTOMER_ID=6;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEEID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='001' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='015' WHERE EMPLOYEEID=5;

SELECT * FROM EMPLOYEE 
;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='003' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='005' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='065' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='045' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='095' WHERE EMPLOYEEID=6;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='071' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='091' WHERE EMPLOYEEID=9;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='041' WHERE CUSTOMER_ID=10;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='006' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT;

