REM   Script: MRNG
REM   K

CREATE TABLE EMPLOYEE ( 
    EMPLOYEEID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    EMAIL_ID varchar (255), 
    PHONE_NUMBER int, 
    HIRING_DATE INT, 
    SALARY INT 
);

INSERT INTO EMPLOYEE VALUES(1,'AHAMED','SUHAIL','ahamedsuhail2412@GMAIL.COM',8220548132,09/08/2022,24000);

INSERT INTO EMPLOYEE VALUES(2,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(3,'AJMUL','KANI','ajmulgani4567@GMAIL.COM',8056570129,18/12/2019,40000);

INSERT INTO EMPLOYEE VALUES(4,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(5,'HARI','HARAN','hariharan4545@GMAIL.COM',8220564563,29/03/2020,30000);

INSERT INTO EMPLOYEE VALUES(6,'JANOFER','NISHA','janofernisha4321@GMAIL.COM',8220568473,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(7,'SATHIS','KUMAR','sathiskumar9045@GMAIL.COM',8220563784,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(8,'RANJITH','KUMAR','ranjithkumar5645@GMAIL.COM',8220567434,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(9,'BASITH','ALI','basithali8745@GMAIL.COM',8220561455,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(10,'TAMIL','SELVI','tamilselvi9845@GMAIL.COM',8220561352,29/09/2018,50000);

SELECT * FROM EMPLOYEE;

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int 
     
);

INSERT INTO DEPARTMENT VALUES(1,'AHAMED SUHAIL','3/79 RAMAZAN STREET ATHIYUTHU','RAMANATHAPURAM','INDIA',623513);

INSERT INTO DEPARTMENT VALUES(2,'SRI KARN','3/98 NEW STREET PANAIKULAM','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(3,'SATHIS KUMAR','4/55S EAST STREET CHITTORKOTTAI','RAMANATHAPURAM','INDIA',623534);

INSERT INTO DEPARTMENT VALUES(4,'JANOFER NISHA','4/R3 WEST STREET PUTHUVALASI','RAMANATHAPURAM','INDIA',623523);

INSERT INTO DEPARTMENT VALUES(5,'RANJITH KUMAR','33/R4 NORTH STREET THERBOKI','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(6,'HARI HARAN','4/4R SOUTH STREET KOVILKARAI','RAMANATHAPURAM','INDIA',623511);

INSERT INTO DEPARTMENT VALUES(7,'AJMUL KANI','3/33L RAMALAN STREET ALAGANKULAM','RAMANATHAPURAM','INDIA',623514);

INSERT INTO DEPARTMENT VALUES(8,'SINDHU SRI','3/34LD KOVIL STREET ATTANKARAI','RAMANATHAPURAM','INDIA',623515);

INSERT INTO DEPARTMENT VALUES(9,'TAMIL SELVI','324D/3W KAVAL STREET MANDAPAM','RAMANATHAPURAM','INDIA',623518);

INSERT INTO DEPARTMENT VALUES(10,'BASITH ALI','3/89L OLD STREET RAMALAN NAGAR','RAMANATHAPURAM','INDIA',623517);

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID=A1 WHERE CUSTOMER_ID=1;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=6;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=7;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=9;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=9;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=5;

SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.DEPARTMENT_ID,EMPLOYEE.DEPARTMENT_ID 
 FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMEN;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ELECT * FROM EMPLOYEE


SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE DROP COLUMN DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT DROP COLUMN DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='012' WHERE CUSTOMER_ID=9;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='015' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='005' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='025' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='06' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='009' WHERE CUSTOMER_ID=6;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEEID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='001' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='015' WHERE EMPLOYEEID=5;

SELECT * FROM EMPLOYEE 
;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='003' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='005' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='065' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='045' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='095' WHERE EMPLOYEEID=6;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='071' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='091' WHERE EMPLOYEEID=9;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='041' WHERE CUSTOMER_ID=10;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='006' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT;

SELECT*FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM CUSTOMERS;

ELECT*FROM DEPARTMENT


ELECT*FROM DEPARTMENT


SELECT * FROM EMPLOYEE;

SELECT*FROM DEPARTMENT;

CREATE TABLE EMPLOYEE ( 
    EMPLOYEEID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    EMAIL_ID varchar (255), 
    PHONE_NUMBER int, 
    HIRING_DATE INT, 
    SALARY INT 
);

INSERT INTO EMPLOYEE VALUES(1,'AHAMED','SUHAIL','ahamedsuhail2412@GMAIL.COM',8220548132,09/08/2022,24000);

INSERT INTO EMPLOYEE VALUES(2,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(3,'AJMUL','KANI','ajmulgani4567@GMAIL.COM',8056570129,18/12/2019,40000);

INSERT INTO EMPLOYEE VALUES(4,'SRI','KARAN','srikaran6545@GMAIL.COM',8220561722,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(5,'HARI','HARAN','hariharan4545@GMAIL.COM',8220564563,29/03/2020,30000);

INSERT INTO EMPLOYEE VALUES(6,'JANOFER','NISHA','janofernisha4321@GMAIL.COM',8220568473,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(7,'SATHIS','KUMAR','sathiskumar9045@GMAIL.COM',8220563784,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(8,'RANJITH','KUMAR','ranjithkumar5645@GMAIL.COM',8220567434,29/09/2019,40000);

INSERT INTO EMPLOYEE VALUES(9,'BASITH','ALI','basithali8745@GMAIL.COM',8220561455,29/09/2020,30000);

INSERT INTO EMPLOYEE VALUES(10,'TAMIL','SELVI','tamilselvi9845@GMAIL.COM',8220561352,29/09/2018,50000);

SELECT * FROM EMPLOYEE;

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int, 
     
);

CREATE TABLE DEPARTMENT ( 
    CUSTOMER_ID int, 
    CONTACT_Name varchar(255), 
    ADDRESS varchar(255), 
    CITY varchar (255), 
    COUNTRY varchar (255), 
    POSTALCODE int 
     
);

INSERT INTO DEPARTMENT VALUES(1,'AHAMED SUHAIL','3/79 RAMAZAN STREET ATHIYUTHU','RAMANATHAPURAM','INDIA',623513);

INSERT INTO DEPARTMENT VALUES(2,'SRI KARN','3/98 NEW STREET PANAIKULAM','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(3,'SATHIS KUMAR','4/55S EAST STREET CHITTORKOTTAI','RAMANATHAPURAM','INDIA',623534);

INSERT INTO DEPARTMENT VALUES(4,'JANOFER NISHA','4/R3 WEST STREET PUTHUVALASI','RAMANATHAPURAM','INDIA',623523);

INSERT INTO DEPARTMENT VALUES(5,'RANJITH KUMAR','33/R4 NORTH STREET THERBOKI','RAMANATHAPURAM','INDIA',623512);

INSERT INTO DEPARTMENT VALUES(6,'HARI HARAN','4/4R SOUTH STREET KOVILKARAI','RAMANATHAPURAM','INDIA',623511);

INSERT INTO DEPARTMENT VALUES(7,'AJMUL KANI','3/33L RAMALAN STREET ALAGANKULAM','RAMANATHAPURAM','INDIA',623514);

INSERT INTO DEPARTMENT VALUES(8,'SINDHU SRI','3/34LD KOVIL STREET ATTANKARAI','RAMANATHAPURAM','INDIA',623515);

INSERT INTO DEPARTMENT VALUES(9,'TAMIL SELVI','324D/3W KAVAL STREET MANDAPAM','RAMANATHAPURAM','INDIA',623518);

INSERT INTO DEPARTMENT VALUES(10,'BASITH ALI','3/89L OLD STREET RAMALAN NAGAR','RAMANATHAPURAM','INDIA',623517);

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID=A1 WHERE CUSTOMER_ID=1;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=6;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=7;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=9;

SELECT * FROM DEPARTMENT 
UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='B1' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE LAST_NAME=1;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='A1' WHERE EMPLOYEEID=9;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=5;

SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=6;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='B1' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE='01/02/22' WHERE EMPLOYEEID=10;

UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT_ID FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.DEPARTMENT_ID,EMPLOYEE.DEPARTMENT_ID 
 FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

SELECT * FROM EMPLOYEE 
SELECT * FROM DEPARTMENT 
UPDATE EMPLOYEE SET HIRING_DATE=01/02/22 WHERE EMPLOYEEID=10;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMEN;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ELECT * FROM EMPLOYEE


SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE DROP COLUMN DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT DROP COLUMN DEPARTMENT_ID;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE DEPARTMENT_ID;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME,LAST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN FIRST_NAME;

ALTER TABLE  EMPLOYEE DROP COLUMN LAST_NAME;

ALTER TABLE DEPARTMENT ADD DEPARTMENT_ID VARCHAR (256);

ALTER TABLE EMPLOYEE ADD DEPARTMENT_ID VARCHAR (256);

UPDATE DEPARTMENT SET DEPARTMENT_ID='001' WHERE CUSTOMER_ID=8;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='012' WHERE CUSTOMER_ID=9;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=10;

UPDATE DEPARTMENT SET DEPARTMENT_ID='015' WHERE CUSTOMER_ID=1;

UPDATE DEPARTMENT SET DEPARTMENT_ID='003' WHERE CUSTOMER_ID=2;

UPDATE DEPARTMENT SET DEPARTMENT_ID='005' WHERE CUSTOMER_ID=3;

UPDATE DEPARTMENT SET DEPARTMENT_ID='025' WHERE CUSTOMER_ID=4;

UPDATE DEPARTMENT SET DEPARTMENT_ID='06' WHERE CUSTOMER_ID=5;

UPDATE DEPARTMENT SET DEPARTMENT_ID='009' WHERE CUSTOMER_ID=6;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE CUSTOMER_ID=1;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEE_ID=1;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='004' WHERE EMPLOYEEID=1;

UPDATE EMPLOYEE SET DEPARTMENT_ID='001' WHERE EMPLOYEEID=2;

UPDATE EMPLOYEE SET DEPARTMENT_ID='015' WHERE EMPLOYEEID=5;

SELECT * FROM EMPLOYEE 
;

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='003' WHERE EMPLOYEEID=7;

UPDATE EMPLOYEE SET DEPARTMENT_ID='005' WHERE EMPLOYEEID=10;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='065' WHERE EMPLOYEEID=3;

UPDATE EMPLOYEE SET DEPARTMENT_ID='045' WHERE EMPLOYEEID=4;

UPDATE EMPLOYEE SET DEPARTMENT_ID='095' WHERE EMPLOYEEID=6;

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET DEPARTMENT_ID='071' WHERE EMPLOYEEID=8;

UPDATE EMPLOYEE SET DEPARTMENT_ID='091' WHERE EMPLOYEEID=9;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='041' WHERE CUSTOMER_ID=10;

SELECT * FROM DEPARTMENT;

UPDATE DEPARTMENT SET DEPARTMENT_ID='006' WHERE CUSTOMER_ID=5;

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.DEPARTMENT_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT;

SELECT* FROM EMPLOYEE;

SELECT* FROM EMPLOYEE;

SELECT* FROM DEPATMENT;

SELECT* FROM DEPARTMENT;

SELECT DEPARTMENT.CUSTOMER_ID,EMPLOYEE.EMPLOYEE_ID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CUSTOMER_ID,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT INNER JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID;

SELECT DEPARTMENT.CONTACT_NAME,EMPLOYEE.EMPLOYEEID 
FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPARTMENT_ID=EMPLOYEE.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT* FROM EMPLOYEE;

SELECT* FROM EMPLOYEE;

SELECT* FROM EMPLOYEE;

SELECT* FROM DEPARTMENT;

SELECT EMPLOYEE.EMPLOYEEID 
FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY EMPLOYEE.SALARY;

SELECT* FROM EMPLOYEE;

SELECT* FROM DEPARTMENT;

SELECT EMPLOYEE.EMPLOYEEID 
FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.CONTACT_NAME ORDER BY EMPLOYEE.SALARY;

SELECT EMPLOYEE.EMPLOYEEID 
FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY EMPLOYEE.SALARY;

SELECT* FROM EMPLOYEE;

SELECT EMPLOYEE.EMAIL_ID 
FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY EMPLOYEE.SALARY;

SELECT EMPLOYEE.EMAIL_ID,DEPARTEMNT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT* FROM DEPARTMENT;

SELECT EMPLOYEE.EMAIL_ID,DEPARTEMENT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT EMPLOYEE.EMAIL_ID,DEPARTMENT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT EMPLOYEE.EMPLOYEEID_ID,DEPARTMENT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT EMPLOYEE.EMPLOYEEIDID,DEPARTMENT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

SELECT EMPLOYEE.EMPLOYEEID,DEPARTMENT.CONTACT_NAME 
FROM DEPARTMENT FULL OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID ORDER BY DEPARTMENT.CONTACT_NAME;

CREATE TABLE PERSONS ( 
    PERSON ID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
);

CREATE TABLE PERSONS ( 
    PERSON ID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int 
);

CREATE TABLE PERSONS ( 
    PERSON ID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int 
);

CREATE TABLE PERSONS ( 
    PERSON ID int, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int 
);

CREATE TABLE CUSTOMER ( 
    PERSON_ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (PERSON_ID) 
);

CREATE TABLE ORDER ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID) 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID) 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

REATE TABLE CUSTOMER ( 


    PERSON_ID int NOT NULL, 


    First_Name varchar(255), 


    Last_Name varchar(255), 


    AGE int, 


    PRIMARY KEY (PERSON_ID) 


);


CREATE TABLE CUSTOMER ( 
    PERSON_ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID) 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_PERSONAL_ID INT FOREIGN KEY REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT  REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT  REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS ( 
    PERSON_ID int NOT NULL, 
    ORDER_DESCRIPTION varchar(255), 
    ORDER_DATE varchar (255), 
    PRICE int, 
    PRIMARY KEY (PERSON_ID), 
    CUSTOMER_ID INT  REFERENCE CUSTOMER(PERSON_ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_(PERSON_ID) INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_(PERSON_ID) INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE CUSTOMERS ( 
    ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (PERSON_ID) 
);

CREATE TABLE CUSTOMERS ( 
    ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (ID) 
);

CREATE TABLE ORDERS( 
PERSON_ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID), 
);

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID)) 
);

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID)) 
);

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID)) 
);

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID))) 
);

); 


CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID));

); 


CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID));

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID), 
CUSTOMER_ID INT REFERENCE CUSTOMER(ID));

DESC EMPLOYEE


CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (PERSON_ID),FOREIGN KEY(ID) REFERENCES CUSTOMERS(ID));

CREATE TABLE ORDERS( 
ID int NOT NULL, 
ORDER_DESCRIPTION varchar(255), 
ORDER_DATE varchar(255), 
PRICE INT, 
PRIMARY KEY (ID),FOREIGN KEY(ID) REFERENCES CUSTOMERS(ID));

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL,23,),(2,'BASITH','ALI',22);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL,23,),(2,'BASITH','ALI',22);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL,23,);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

DESC TABLE CUSTOMERS


CREATE TABLE CUSTOMERS ( 
    ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (ID) 
);

INSERT INTO CUSTOMERS VALUES(1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES (1,'AHAMED','SUHAIL',23,);

DESC CUSTOMERS


INSERT INTO CUSTOMERS VALUES ('1','AHAMED','SUHAIL',23,);

CREATE TABLE CUSTOMERSS ( 
    ID int NOT NULL, 
    First_Name varchar(255), 
    Last_Name varchar(255), 
    AGE int, 
    PRIMARY KEY (ID) 
);

INSERT INTO CUSTOMERSS VALUES ('1','AHAMED','SUHAIL',23,);

INSERT INTO CUSTOMERS VALUES ('1','AHAMED','SUHAIL',23);

INSERT INTO CUSTOMERS VALUES ('2','BASITH','ALI',22);

INSERT INTO CUSTOMERS VALUES ('3','HAREESH','WARAN',24);

NSERT INTO CUSTOMERS VALUES ('4','FARHAN','SYED',24);


INSERT INTO CUSTOMERS VALUES ('4','FARHAN','SYED',24);

INSERT INTO CUSTOMERS VALUES ('4','KABIL','DEV',24);

INSERT INTO CUSTOMERS VALUES ('4','KABIL','DEV',24);

INSERT INTO CUSTOMERS VALUES ('4','KABIL','DEV',24);

SELECT*FROM CUSTOMERS;

NSERT INTO ORDERS VALUES ('4','LG3','1/JUN/22',22400);


NSERT INTO ORDERS VALUES ('4','LG3','1/JUN/22',22400);


NSERT INTO ORDERS VALUES ('4','LG3','1/JUN/22',22400);


INSERT INTO ORDERS VALUES ('4','LG3','1/JUN/22',22400);

SELECT*FROM ORDERS 
;

    PRIMARY KEY (ID) 


); 


INSERT INTO CUSTOMERS VALUES ('4','KABIL','DEV',24);

DESC CUSTOMERS


SELECT*FROM CUSTOMERS 
;

SELECT*FROM CUSTOMERS;

INSERT INTO CUSTOMERS VALUES ('5','SIVA','BALAN',24);

INSERT INTO CUSTOMERS VALUES ('6','SIVA','NESAN',21);

INSERT INTO CUSTOMERS VALUES ('7','SENTHIL','KUMAR',31);

INSERT INTO CUSTOMERS VALUES ('8','PERUML','VALAVAN',31);

NSERT INTO CUSTOMERS VALUES ('9','SELVA','PERUMAL',31);


INSERT INTO CUSTOMERS VALUES ('9','SELVA','PERUMAL',31);

INSERT INTO CUSTOMERS VALUES ('10','KALAI','SELVI',21);

INSERT INTO CUSTOMERS VALUES ('10','KALAI','SELVI',21);

SELECT*FROM CUSTOMERS;

SELECT*FROM ORDERS;

INSERT INTO ORDERS VALUES ('5','LG4','1/FEB/23',22800);

INSERT INTO ORDERS VALUES ('11','LG12','24/DEC/20',12800);

SELECT*FROM ORDERS;

INSERT INTO ORDERS VALUES ('11','LG12','24/DEC/20',12800);

INSERT INTO ORDERS VALUES ('10','LG12','24/DEC/20',12800);

INSERT INTO ORDERS VALUES ('13','LG12','24/DEC/20',12800);

INSERT INTO ORDERS VALUES ('1','LG82','24/SEP/20',12700);

SELECT*FROM ORDERS;

SELECT*FROM CUSTOMERS;

SELECT CUSTOMERS.FIRST_NAME,ORDERS.ORDER_DESCRIPTION 
FROM CUSTOMERS INNER JOIN ORDERS ON CUSTOMERS.ID=ORDSERS.ID;

SELECT*FROM ORDERS;

SELECT*FROM ORDERS;

ALTER TABLE ORDERS RENAME ID TO CUSTOMER_ID;

ALTER TABLE ORDERS RENAME ID TO CUSTOMER_ID;

ALTER TABLE ORDERS RENAME ID TO CUSTOMER_ID;

ALTER TABLE ORDERS RENAME ID TO CUSTOMER_ID;

ALTER TABLE ORDERS RENAME COLUMN ID TO CUSTOMER_ID;

SELECT*FROM ORDERS;

ALTER TABLE CUSTOMERS RENAME COLUMN ID TO CUSTOMER_ID;

SELECT*FROM CUSTOMERS;

SELECT * FROM DEPARTMENT;

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

SELECT * FROM EMPLOYEE;

ELECT * FROM ORDERS


ELECT * FROM ORDERS


SELECT * FROM ORDERS;

